### ISSUE TITLE
Cannot open context menu on Source folder in Split View

### ISSUE THREAD

**Issue by jayrulez** [apistol78/traktor#11]
Switch the database view to Split mode.
Select the source folder and right click to invoke the context menu.
The menu does not open.

If you switch to hierarchy view and try to do the same then this works.

**Comment by apistol78** [comment]
Hm, cannot repro this. The context menu shows in both the group hierarchy and in the instance panel in Split mode.

**Comment by jayrulez** [comment]
This happens if the group wasn't previously selected.

Try this:
Open the editor.
Bring your cursor over the database Source folder.
Without selecting it with LMB, use RMB to try to open the context menu.
It will not open.

The behaviour I was expecting is that RMB would cause the Source folder to be selected, then invoke the context menu on it.
At least that's how things behave in Windows explorer for example.

**Comment by apistol78** [comment]
Should be fixed in f323bac4

**Comment by jayrulez** [comment]
This UX feels a lot better now. Thank you!
