### ISSUE TITLE
Restore scene state after play-stop sequence

### ISSUE THREAD

**Issue by jayrulez** [apistol78/traktor#19]
If I add a dynamic rigid body to the scene and press play, it will start falling.
If I press the stop button, the rigid body does not return to the original position before play was pressed.

If I close the scene and open it again, then the rigid body is in the correct position.

It seems play-stop sequence does not reset the scene state (at least visually) to the state before playing.

**Comment by apistol78** [comment]
There is a rewind button to the left of play which reset scene state.
