### ISSUE TITLE
Editor Malfunction?

### ISSUE THREAD

**Issue by Jxqal** [apistol78/traktor#5]
I have a little problem, when building the editor. i Completed all steps, using the Scripts. When i try to build the Traktor.Editor.App, i get the following error:

![Screenshot 2024-02-23 162140](https://github.com/apistol78/traktor/assets/115593280/669eaed1-eab3-4bd4-b2fc-7e8387737130)

And the Editor window looks like this:

![Screenshot 2024-02-23 162201](https://github.com/apistol78/traktor/assets/115593280/a661c0bc-f8b3-4c68-a521-e99676a4873d)
I tried every button, but nothing Changes.
Hopefully i can get some help

**Comment by apistol78** [comment]
Hi Jxqal!
Seems to be an issue with either missing Vulkan dependencies or broken Traktor binaries.
If you could provide some logfiles from the editor, found in the C:\Users\<user>\AppData\LocalLow\Traktor\Editor\Logs folder, it would be great.
Thanks!

**Comment by Jxqal** [comment]
Hello! I searched my folders, and found this:

![Screenshot 2024-02-24 183602](https://github.com/apistol78/traktor/assets/115593280/c113c848-0128-4fee-a098-451bd48c37e7)

Maybe you could provide me with the name of the Log you need? that would make it easier to find it, since i have a lot of editor and log folders. I saved them on my D drive. Thanks in advance!

**Comment by apistol78** [comment]
The log file sequence numbered and is named "Editor_<number>.log" in the aforementioned directory.
I realize the name isn't super search-friendly but I hope it helps you locate them.

**Comment by apistol78** [comment]
Any progress?
