### ISSUE TITLE
Database Rename group does not work in SplitView

### ISSUE THREAD

**Issue by jayrulez** [apistol78/traktor#8]
https://github.com/apistol78/traktor/blob/4edaa559b715970e7e83633a9d1d1190e537f42e/code/Editor/App/DatabaseView.cpp#L634
The variable treeItem is never set in the  branch:
```else if (viewMode == 1)	// Split```

So the logic here:
```
		else if (command == L"Editor.Database.Rename")	// Rename
		{
			if (treeItem)
				treeItem->edit();
		}
```
will not be executed.

**Comment by apistol78** [comment]
Thanks for reporting this issue. It's fixed in 913aa35e.
